version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_8_0
    ports:
      - 3308:3306
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword2024
      MYSQL_DATABASE: ava_ns_typeorm
      MYSQL_PASSWORD: P@ssword2024
    volumes:
      - ./db_data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ns_phpmyadmin
    # restart: always
    ports:
      - 8090:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: P@ssword2024
      UPLOAD_LIMIT: 20M
